import Head from 'next/head';

import { Feed, Sidebar, Widgets } from '../components';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <main className="flex min-h-screen mx-auto">
        <Sidebar />
        <Feed />
        <Widgets />
      </main>
    </div>
  );
}
